sudo: required
dist: bionic
language: cpp

os:
  - linux

compiler:
  - g++
  - clang

before_script:
  - g++ --version
  - gcov --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./TravisTest-ut


after_success:
  - bash <(curl -s https://codecov.io/bash)
